feat: add console e2e test into vdp
instill-ai/vdp pull request #148
Opened 2022-09-23 11:23 UTC by EiffelFly

Because

- The console integration test is ready

This commit

- add console e2e test into vdp

2022-10-26 12:40 UTC, pinglin requested changes
The integration-test will be blocked by `  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.` Does playwright provide some sort of flag to bypass this?

```
Running 141 tests using 1 worker
  1) [chromium] › pipeline.spec.ts:216:3 › Async pipeline with new source, destination and local model › should create async pipeline 

    Test timeout of 60000ms exceeded.

    locator.fill: Target closed
    =========================== logs ===========================
    waiting for selector "input#id"
    ============================================================

      291 |
      292 |     // Should input destination id
    > 293 |     await destinationIdField.fill(destinationId);
          |                              ^
      294 |
      295 |     // Should select destination type - Scylla
      296 |     const keyspaceField = page.locator("input#keyspace");

        at /Users/Pinglin/Workspace/instill/vdp/dev/console/integration-test/pipeline.spec.ts:293:30
        at /Users/Pinglin/Workspace/instill/vdp/dev/console/node_modules/@playwright/test/lib/workerRunner.js:426:9
        at TestInfoImpl._runFn (/Users/Pinglin/Workspace/instill/vdp/dev/console/node_modules/@playwright/test/lib/testInfo.js:166:7)
        at /Users/Pinglin/Workspace/instill/vdp/dev/console/node_modules/@playwright/test/lib/workerRunner.js:376:26
        at TimeoutManager.runWithTimeout (/Users/Pinglin/Workspace/instill/vdp/dev/console/node_modules/@playwright/test/lib/timeoutManager.js:73:7)
        at TestInfoImpl._runWithTimeout (/Users/Pinglin/Workspace/instill/vdp/dev/console/node_modules/@playwright/test/lib/testInfo.js:154:26)
        at WorkerRunner._runTest (/Users/Pinglin/Workspace/instill/vdp/dev/console/node_modules/@playwright/test/lib/workerRunner.js:356:5)
        at WorkerRunner.runTestGroup (/Users/Pinglin/Workspace/instill/vdp/dev/console/node_modules/@playwright/test/lib/workerRunner.js:218:11)
        at process.<anonymous> (/Users/Pinglin/Workspace/instill/vdp/dev/console/node_modules/@playwright/test/lib/worker.js:88:5)

    Pending operations:
      - locator.fill at integration-test/pipeline.spec.ts:293:30


  Slow test file: [chromium] › pipeline.spec.ts (1m)
  Slow test file: [chromium] › model.spec.ts (56s)
  Slow test file: [webkit] › model.spec.ts (49s)
  Slow test file: [firefox] › model.spec.ts (46s)
  Slow test file: [firefox] › pipeline.spec.ts (22s)
  Consider splitting slow test files to speed up parallel execution

  1 flaky
    [chromium] › pipeline.spec.ts:216:3 › Async pipeline with new source, destination and local model › should create async pipeline 
  140 passed (6m)

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.
```

2022-10-26 12:40 UTC, pinglin commented on Makefile
> +	sed 's/CFG_SERVER_PORT: 8083/CFG_SERVER_PORT: 8083\n      CFG_SERVER_ITMODE: "true"/g' docker-compose-dev.yml > /tmp/docker-compose-integration-test.yml
```suggestion
	@sed 's/CFG_SERVER_PORT: 8083/CFG_SERVER_PORT: 8083\n      CFG_SERVER_ITMODE: "true"/g' docker-compose-dev.yml > /tmp/docker-compose-integration-test.yml
```

2022-10-26 12:40 UTC, pinglin commented on Makefile
> +	sed 's/CFG_SERVER_PORT: 8083/CFG_SERVER_PORT: 8083\n      CFG_SERVER_ITMODE: "true"/g' docker-compose-dev.yml > /tmp/docker-compose-integration-test.yml
Please put `@rm /tmp/docker-compose-integration-test.yml` after `@make down`

2022-10-26 14:36 UTC, EiffelFly commented on Makefile
> +	sed 's/CFG_SERVER_PORT: 8083/CFG_SERVER_PORT: 8083\n      CFG_SERVER_ITMODE: "true"/g' docker-compose-dev.yml > /tmp/docker-compose-integration-test.yml
https://github.com/instill-ai/console/pull/293

Playwright will output very simple result now~

2022-10-26 15:47 UTC, pinglin requested changes
Looks the console integration test doesn't clean up the created connectors before leaving. This will cause pipeline-backend integration test to fail.
```
     █ setup

       █ Connector Backend API: Create a http source connector

         ✗ POST /v1alpha/source-connectors response status for creating HTTP source connector 201
          ↳  0% — ✓ 0 / ✗ 1

       █ Connector Backend API: Create a http destination connector

         ✗ POST /v1alpha/destination-connectors response status for creating HTTP destination connector 201
          ↳  0% — ✓ 0 / ✗ 1
```

2022-10-27 00:36 UTC, xiaofei-du commented
when running the integration test, the test `[Async destination › should create async destination` is flakey.

![image](https://user-images.githubusercontent.com/66248476/198163929-11a5e7d6-e6c1-4d59-97df-f5e6ba25f4e1.png)

2022-10-27 05:11 UTC, EiffelFly commented
I would consider enter slowMo mode too for destination test.

2022-10-27 07:25 UTC, EiffelFly commented
@xiaofei-du @pinglin 

https://github.com/instill-ai/console/pull/295

This PR further stabilize the integration-test and clean up connectors after each test.

2022-10-27 08:51 UTC, xiaofei-du commented
connector-backend errors

```
 █ Connector API: List destination connectors

       ✓ GET /v1alpha/destination-connectors response status is 200
       ✗ GET /v1alpha/destination-connectors response destination_connectors array is 0 length
        ↳  0% — ✓ 0 / ✗ 1
       ✓ GET /v1alpha/destination-connectors response next_page_token is empty
       ✗ GET /v1alpha/destination-connectors response total_size is 0
        ↳  0% — ✓ 0 / ✗ 1
       ✓ POST /v1alpha/destination-connectors x10 response status 201
       ✓ GET /v1alpha/destination-connectors response has destination_connectors array
       ✗ GET /v1alpha/destination-connectors response has total_size = 10
        ↳  0% — ✓ 0 / ✗ 1
       ✓ GET /v1alpha/destination-connectors?page_size=0 response status is 200    
```

2022-11-17 07:56 UTC, Phelan164 approved these changes
LGTM

2022-11-24 00:14 UTC, pinglin approved these changes
LGTM

2022-11-24 00:16 UTC, merged