feat: update integration test
instill-ai/vdp pull request #85
Opened 2022-02-23 19:13 UTC by Phelan164

Because

- Need integration test to make sure feature work correctly

This commit

- Add integration test for model-backend and update for pipeline-backend

2022-02-23 21:57 UTC, xiaofei-du requested changes
I have left some comments. Two more questions:

1. Can we delete all the models in the `teardown` function in `model-backend-rest.js` like deleting all pipelines in `pipeline-backend-rest.js`. This can make sure the model-backend tests won't affect other tests.

2. In `model-backend-rest.js`, I see that we have covered tests for `CLASSIFICATION` and `DETECTION` 👍 . Can we also add similar tests to cover creating a model without specifying any CV task and making inferences with this model? I think it will make the basic tests more complete.

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/pipeline-backend-rest.js
>  const dogImg = open(`${__ENV.TEST_FOLDER_ABS_PATH}/dog.jpg`, "b");
```suggestion
const dogImg = open(`${__ENV.TEST_FOLDER_ABS_PATH}/tests/integration-tests/data/dog.jpg`, "b");
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/pipeline-backend-rest.js
> +const model_name = "yolov4"
```suggestion
const model_name = pipelineConstants.detectionModel.name;
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/pipeline-backend-rest.js
> +const model_name = "yolov4"
Since we are not using yolov4 as the test model any more, let's also change the model name in `tests/integration-tests/pipeline-backend-constants.js`
```JavaScript
export const detectionModel = {
  name: "dummy-det",
  version: 1,
};

export const detectionRecipe = {
  recipe: {
    source: {
      type: "Direct",
    },
    model: [detectionModel],
    destination: {
      type: "Direct",
    },
  },
};
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/pipeline-backend-rest.js
>  const dogImg = open(`${__ENV.TEST_FOLDER_ABS_PATH}/dog.jpg`, "b");
In `pipeline-backend-rest.js`, change `group("Pipelines API: Trigger a pipeline with classification model", () => {` to `    group("Pipelines API: Trigger a pipeline", () => {`

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/model-backend-rest.js
> +          r.status === 200 // TODO: update status to 201
```suggestion
          r.status === 200 // TODO: update status to 204
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/model-backend-rest.js
> +          r.status === 200 // TODO: update status to 201
```suggestion
          r.status === 200 // TODO: update status to 204
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/model-backend-rest.js
> +          r.status === 200 // TODO: update status to 201
```suggestion
          r.status === 200 // TODO: update status to 204
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/model-backend-rest.js
> +          r.status === 200 // TODO: update status to 201
```suggestion
          r.status === 200 // TODO: update status to 204
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/model-backend-rest.js
> +          r.status === 200 // TODO: update status to 201
```suggestion
          r.status === 200 // TODO: update status to 204
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/model-backend-rest.js
> +          r.status === 200 // TODO: update status to 201
```suggestion
          r.status === 200 // TODO: update status to 204
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/model-backend-rest.js
> +          r.status === 200 // TODO: update status to 201
```suggestion
          r.status === 200 // TODO: update status to 204
```

2022-02-23 21:57 UTC, xiaofei-du commented on tests/integration-tests/model-backend-rest.js
> +          r.status === 200 // TODO: update status to 201
```suggestion
          r.status === 200 // TODO: update status to 204
```

2022-02-24 03:12 UTC, Phelan164 commented
@xiaofei-du 
>Can we delete all the models in the teardown function in model-backend-rest.js like deleting all pipelines in pipeline-backend-rest.js. This can make sure the model-backend tests won't affect other tests.

In each test case, I always delete the created model. Why could not delete in teardown? Because many models created during testing (model name is random string) then need delete in each test case to prevent impact to other test cases (example list model will be return much more, etc)

2022-02-24 03:12 UTC, Phelan164 commented
>In model-backend-rest.js, I see that we have covered tests for CLASSIFICATION and DETECTION 👍 . Can we also add similar tests to cover creating a model without specifying any CV task and making inferences with this model? I think it will make the basic tests more complete.

yes, agree. It missing. I will add that

2022-02-24 09:17 UTC, pinglin requested changes

2022-02-24 09:17 UTC, pinglin commented on docker-compose.yml
> +    image: instill/model-backend:dev
@Phelan164 We use the release version in vdp docker-compose.

2022-02-24 09:17 UTC, pinglin commented on docker-compose.yml
> +    image: instill/model-backend:dev
@Phelan164 For the same reason as the above comment, please drop this change.

2022-02-24 11:37 UTC, xiaofei-du commented
> 



> @xiaofei-du
> 
> > Can we delete all the models in the teardown function in model-backend-rest.js like deleting all pipelines in pipeline-backend-rest.js. This can make sure the model-backend tests won't affect other tests.
> 
> In each test case, I always delete the created model. Why could not delete in teardown? Because many models created during testing (model name is random string) then need delete in each test case to prevent impact to other test cases (example list model will be return much more, etc)

Yeah, we should delete the created resource in each test case. But when other people contribute tests, they may forget it. So filling the `teardown` process is just to add the extra security.

2022-02-24 19:00 UTC, xiaofei-du approved these changes
LGTM 👍

2022-02-24 19:01 UTC, pinglin approved these changes

2022-02-24 19:02 UTC, bochengyang approved these changes
LGTM 🚀

2022-02-24 19:02 UTC, bochengyang commented on tests/integration-tests/helpers.js
> +export const base64_image = "/9j/4AAQSkZJRgABAQEAYABgAAD/4TgsRXhpZgAATU0AKgAAAAgABgALAAIAAAAmAAAIYgESAAMAAAABAAEAAAExAAIAAAAmAAAIiAEyAAIAAAAUAAAIrodpAAQAAAABAAAIwuocAAcAAAgMAAAAVgAAEUYc6gAAAAgAAAAAAA
You may use the code as follow to read and encode as base64 not hard-coded

Read file

```javascript
const fooBarImg = open(`${__ENV.TEST_FOLDER_ABS_PATH}/cubo.jpg`, "b");
```

Encode to base64

```javascript
  contents: [
    {
      base64: encoding.b64encode(fooBarImg, "b"),
    },
  ],
```

2022-02-24 19:02 UTC, bochengyang commented on docker-compose.yml
> +    image: instill/model-backend:dev
This should not commit, instead, you should have a specified alpha version

2022-02-24 19:02 UTC, bochengyang commented on docker-compose.yml
> +    image: instill/model-backend:dev
This should not commit, instead, you should have a specified alpha version

2022-02-24 19:02 UTC, bochengyang commented on tests/integration-tests/pipeline-backend-rest.js
> +const model_name = "yolov4"
I can do that, thanks for your suggestion

2022-02-24 19:02 UTC, bochengyang commented on tests/integration-tests/pipeline-backend-rest.js
>  const dogImg = open(`${__ENV.TEST_FOLDER_ABS_PATH}/dog.jpg`, "b");
Done

2022-02-24 19:02 UTC, bochengyang commented on tests/integration-tests/pipeline-backend-rest.js
>  const dogImg = open(`${__ENV.TEST_FOLDER_ABS_PATH}/dog.jpg`, "b");
Since the data is prepared inside the `test//integration-tests/data` folder, I will also remove the following code in Makefile.

```bash
@curl -o yolov4-onnx-cpu.zip https://artifacts.instill.tech/vdp/sample-models/yolov4-onnx-cpu.zip
@curl -o dog.jpg https://artifacts.instill.tech/dog.jpg
```

```bash
@rm yolov4-onnx-cpu.zip
@rm dog.jpg
```

2022-02-24 19:06 UTC, merged

2022-02-24 19:09 UTC, bochengyang commented
close #50